# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmplifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=80, unique=True)),
                ('email_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('is_account_active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'amplify_user',
            },
        ),
    ]
